receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  zipkin:

processors:
  batch:
    timeout: 10s

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure_skip_verify: true
      insecure: true
  zipkin:
    endpoint: 'http://zipkin:9411/api/v2/spans'
  loki:
    endpoint: 'http://loki:3100/loki/api/v1/push'
  debug:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [zipkin, otlp]
      processors: [batch]
      exporters: [zipkin, otlp, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug]
